---
title: "nltt statistic"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

```{r echo=FALSE, include=FALSE, cache=FALSE}
library(dmea)
library("plotrix")
```


```{r}
ltt = matrix(0,ncol=100,nrow=100)
k=1
m=NULL
for(i in 1:100){
  s1 = sim_phyl(seed=i)
  for(j in i:100){
    s2 = sim_phyl(seed=j)
    l = ltt_stat(s1$newick,s2$newick)
    ltt[i,j] = l
    ltt[j,i] = l
    if(j!=i){
      m[k] = l
      k=k+1
    }
  }
}

```


```{r}
 color2D.matplot(ltt,c(1,0),c(0,0),c(0,1),show.legend=TRUE,xlab="Columns",ylab="Rows",main="2D matrix plot")
```

```{r}
qplot(m, geom="histogram")
summary(m)
```


and the next 100 seeds?

```{r}
ltt = matrix(0,ncol=100,nrow=100)
k=1
m=NULL
for(i in 1:100){
  s1 = sim_phyl(seed=100+i)
  for(j in i:100){
    s2 = sim_phyl(seed=100+j)
    l = ltt_stat(s1$newick,s2$newick)
    ltt[i,j] = l
    ltt[j,i] = l
    if(j!=i){
      m[k] = l
      k=k+1
    }
  }
}

```


```{r}
 color2D.matplot(ltt,c(1,0),c(0,0),c(0,1),show.legend=TRUE,xlab="Columns",ylab="Rows",main="2D matrix plot")
```

```{r}
qplot(m, geom="histogram")
summary(m)
```


which is the closest tree to seed=3 tree?

```{r}
m=NULL
s1 <- sim_phyl(seed=3)
for(i in 1:1000){
  s2 <-sim_phyl(4+i)
  m[i] <- ltt_stat(s1$newick,s2$newick)
}
```


```{r}
qplot(m, geom="histogram")
summary(m) 
```
