---
title: "hgitli2"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

```{r echo=FALSE, include=FALSE,cache=FALSE}
library(dmea)
```

## Method 1

```{r sim1, message=FALSE}
n_sim = 1000
n_trees = 10
MP = matrix(nrow=n_sim,ncol=3)
RP = matrix(nrow=n_sim,ncol=3)
p = proc.time()
for(i in 1:n_sim){
  est = sim_est(n_trees=n_trees,rec_method=1,seed=i)
  RP[i,] = est$real
  MP[i,] = est$est
}
print(proc.time()-p)

par_est_vis(P=MP,par=1,PR=RP)
par_est_vis(P=MP,par=2,PR=RP)
par_est_vis(P=MP,par=3,PR=RP)

```

```{r sum1}
summary(MP)
```

parallel:

```{r sim1p, message=FALSE }
no_cores <- detectCores()- 1 
cl <- makeCluster(no_cores)
registerDoParallel(cl)

n_sim = 1000
n_trees = 10
MP = matrix(nrow=n_sim,ncol=3)
RP = matrix(nrow=n_sim,ncol=3)
p = proc.time()
ests <- foreach(i = 1:n_sim, .combine=data.frame,.packages='dmea') %dopar% sim_est(n_trees=n_trees,rec_method=1,seed=i)
print(proc.time()-p)

for (i in 1:n_sim){
  RP[i,] = ests[,(2*i-1)]
  MP[i,] = ests[,2*i]
}
stopCluster(cl)
par_est_vis(P=MP,par=1,PR=RP)
par_est_vis(P=MP,par=2,PR=RP)
par_est_vis(P=MP,par=3,PR=RP)

```

```{r sum1p}
summary(MP)
```


now for sets of 100 trees 


```{r sim1pm, message=FALSE }
no_cores <- detectCores()- 1 
cl <- makeCluster(no_cores)
registerDoParallel(cl)

n_sim = 1000
n_trees = 100
MP = matrix(nrow=n_sim,ncol=3)
RP = matrix(nrow=n_sim,ncol=3)
p = proc.time()
ests <- foreach(i = 1:n_sim, .combine=data.frame,.packages='dmea') %dopar% sim_est(n_trees=n_trees,rec_method=1,seed=i)
print(proc.time()-p)

for (i in 1:n_sim){
  RP[i,] = ests[,(2*i-1)]
  MP[i,] = ests[,2*i]
}
stopCluster(cl)
par_est_vis(P=MP,par=1,PR=RP)
par_est_vis(P=MP,par=2,PR=RP)
par_est_vis(P=MP,par=3,PR=RP)

```

```{r sum1pm}
summary(MP)
```

## Method 2

```{r sim2, message=FALSE}
n_sim = 400
n_trees = 10
MP = matrix(nrow=n_sim,ncol=3)
RP = matrix(nrow=n_sim,ncol=3)
p = proc.time()
for(i in 1:n_sim){
  set.seed(i)
  est = sim_est(n_trees=n_trees,rec_method=2)
  RP[i,] = est$real
  MP[i,] = est$est
}
print(proc.time()-p)

par_est_vis(P=MP,par=1,PR=RP)
par_est_vis(P=MP,par=2,PR=RP)
par_est_vis(P=MP,par=3,PR=RP)

```

```{r sum2}
summary(MP)
```

## Method 3

```{r sim3, message=FALSE}
n_sim = 400
n_trees = 10
MP = matrix(nrow=n_sim,ncol=3)
RP = matrix(nrow=n_sim,ncol=3)
p = proc.time()
for(i in 1:n_sim){
  set.seed(i)
  est = sim_est(n_trees=n_trees,rec_method=3)
  RP[i,] = est$real
  MP[i,] = est$est
}
print(proc.time()-p)

par_est_vis(P=MP,par=1,PR=RP)
par_est_vis(P=MP,par=2,PR=RP)
par_est_vis(P=MP,par=3,PR=RP)

```

```{r sum3}
summary(MP)
```

more simmulations

```{r sim3p, message=FALSE }
no_cores <- detectCores()- 1 
cl <- makeCluster(no_cores)
registerDoParallel(cl)

n_sim = 1000
n_trees = 10
MP = matrix(nrow=n_sim,ncol=3)
RP = matrix(nrow=n_sim,ncol=3)
p = proc.time()
ests <- foreach(i = 1:n_sim, .combine=data.frame,.packages='dmea') %dopar% sim_est(n_trees=n_trees,rec_method=3,seed=i)
print(proc.time()-p)

for (i in 1:n_sim){
  RP[i,] = ests[,(2*i-1)]
  MP[i,] = ests[,2*i]
}
stopCluster(cl)
par_est_vis(P=MP,par=1,PR=RP)
par_est_vis(P=MP,par=2,PR=RP)
par_est_vis(P=MP,par=3,PR=RP)

```

```{r sum3p}
summary(MP)
```
# Importance sampling


## Method 1

```{r sim4, message=FALSE}
n_sim = 400
n_trees = 10
MP = matrix(nrow=n_sim,ncol=3)
RP = matrix(nrow=n_sim,ncol=3)
p = proc.time()
for(i in 1:n_sim){
  set.seed(i)
  est = sim_est(n_trees=n_trees,rec_method=1,impsam = TRUE)
  RP[i,] = est$real
  MP[i,] = est$est
}
print(proc.time()-p)

par_est_vis(P=MP,par=1,PR=RP)
par_est_vis(P=MP,par=2,PR=RP)
par_est_vis(P=MP,par=3,PR=RP)

```

```{r}
par_est_vis(P=MP[MP[,1]<3,],par=1,PR=RP[MP[,1]<3,])
par_est_vis(P=MP[MP[,1]<3,],par=2,PR=RP[MP[,1]<3,])
par_est_vis(P=MP[MP[,1]<3,],par=3,PR=RP[MP[,1]<3,])
```

```{r sum4}
summary(MP[MP[,1]<3,])
```

more simulations (but in parallel)

```{r sim4p, message=FALSE }
no_cores <- detectCores()- 1 
cl <- makeCluster(no_cores)
registerDoParallel(cl)

n_sim = 1000
n_trees = 10
MP = matrix(nrow=n_sim,ncol=3)
RP = matrix(nrow=n_sim,ncol=3)
p = proc.time()
ests <- foreach(i = 1:n_sim, .combine=data.frame,.packages='dmea') %dopar% sim_est(n_trees=n_trees,rec_method=1,seed=i,impsam=TRUE)
print(proc.time()-p)

for (i in 1:n_sim){
  RP[i,] = ests[,(2*i-1)]
  MP[i,] = ests[,2*i]
}
stopCluster(cl)
par_est_vis(P=MP,par=1,PR=RP)
par_est_vis(P=MP,par=2,PR=RP)
par_est_vis(P=MP,par=3,PR=RP)

```

```{r sum4p}
summary(MP)
```

```{r}
par_est_vis(P=MP[MP[,1]<3,],par=1,PR=RP[MP[,1]<3,])
par_est_vis(P=MP[MP[,1]<3,],par=2,PR=RP[MP[,1]<3,])
par_est_vis(P=MP[MP[,1]<3,],par=3,PR=RP[MP[,1]<3,])
```

```{r sum4p0}
summary(MP[MP[,1]<3,])
```

more trees?

```{r sim4pm, message=FALSE }
no_cores <- detectCores()- 1 
cl <- makeCluster(no_cores)
registerDoParallel(cl)

n_sim = 1000
n_trees = 100
MP = matrix(nrow=n_sim,ncol=3)
RP = matrix(nrow=n_sim,ncol=3)
p = proc.time()
ests <- foreach(i = 1:n_sim, .combine=data.frame,.packages='dmea') %dopar% sim_est(n_trees=n_trees,rec_method=1,seed=i,impsam=TRUE)
print(proc.time()-p)

for (i in 1:n_sim){
  RP[i,] = ests[,(2*i-1)]
  MP[i,] = ests[,2*i]
}
stopCluster(cl)
par_est_vis(P=MP,par=1,PR=RP)
par_est_vis(P=MP,par=2,PR=RP)
par_est_vis(P=MP,par=3,PR=RP)

```

```{r sum4pm}
summary(MP)
```

```{r sum4p0m1}
par_est_vis(P=MP[MP[,1]<3,],par=1,PR=RP[MP[,1]<3,])
par_est_vis(P=MP[MP[,1]<3,],par=2,PR=RP[MP[,1]<3,])
par_est_vis(P=MP[MP[,1]<3,],par=3,PR=RP[MP[,1]<3,])
```

```{r sum4p0m}
summary(MP[MP[,1]<3,])
```

more trees?

```{r, simoiv}
no_cores <- detectCores()- 1 
cl <- makeCluster(no_cores)
registerDoParallel(cl)

n_sim = 300
n_trees = 1000
MP = matrix(nrow=n_sim,ncol=3)
RP = matrix(nrow=n_sim,ncol=3)
p = proc.time()
ests <- foreach(i = 1:n_sim, .combine=data.frame, .packages='dmea') %dopar% sim_est(n_trees=n_trees, rec_method=1, seed=i, impsam=TRUE)
print(proc.time()-p)

for (i in 1:n_sim){
  RP[i,] = ests[,(2*i-1)]
  MP[i,] = ests[,2*i]
}
stopCluster(cl)
par_est_vis(P=MP,par=1,PR=RP)
par_est_vis(P=MP,par=2,PR=RP)
par_est_vis(P=MP,par=3,PR=RP)

```

```{r}
summary(MP)
```

```{r sum4p0m11}
par_est_vis(P=MP[MP[,1]<3,],par=1,PR=RP[MP[,1]<3,])
par_est_vis(P=MP[MP[,1]<3,],par=2,PR=RP[MP[,1]<3,])
par_est_vis(P=MP[MP[,1]<3,],par=3,PR=RP[MP[,1]<3,])
```

```{r sum4p0m2}
summary(MP[MP[,1]<3,])
```

```{r}
dim(MP)
dim(MP[MP[,1]<3,])
```

## Method 2

```{r sim5, message=FALSE}
n_sim = 400
n_trees = 10
MP = matrix(nrow=n_sim,ncol=3)
RP = matrix(nrow=n_sim,ncol=3)
p = proc.time()
for(i in 1:n_sim){
  set.seed(i)
  est = sim_est(n_trees=n_trees,rec_method=2,impsam = TRUE)
  RP[i,] = est$real
  MP[i,] = est$est
}
print(proc.time()-p)

par_est_vis(P=MP,par=1,PR=RP)
par_est_vis(P=MP,par=2,PR=RP)
par_est_vis(P=MP,par=3,PR=RP)

```

```{r}
par_est_vis(P=MP[MP[,1]<3,],par=1,PR=RP[MP[,1]<3,])
par_est_vis(P=MP[MP[,1]<3,],par=2,PR=RP[MP[,1]<3,])
par_est_vis(P=MP[MP[,1]<3,],par=3,PR=RP[MP[,1]<3,])
```

```{r sum5}
summary(MP[MP[,1]<3,])
```

## Method 3

```{r sim6, message=FALSE}
n_sim = 400
n_trees = 10
MP = matrix(nrow=n_sim,ncol=3)
RP = matrix(nrow=n_sim,ncol=3)
p = proc.time()
for(i in 1:n_sim){
  set.seed(i)
  est = sim_est(n_trees=n_trees,rec_method=3,impsam = TRUE)
  RP[i,] = est$real
  MP[i,] = est$est
}
print(proc.time()-p)

par_est_vis(P=MP,par=1,PR=RP)
par_est_vis(P=MP,par=2,PR=RP)
par_est_vis(P=MP,par=3,PR=RP)

```

```{r}
par_est_vis(P=MP[MP[,1]<3,],par=1,PR=RP[MP[,1]<3,])
par_est_vis(P=MP[MP[,1]<3,],par=2,PR=RP[MP[,1]<3,])
par_est_vis(P=MP[MP[,1]<3,],par=3,PR=RP[MP[,1]<3,])
```

```{r sum6}
summary(MP[MP[,1]<3,])
```


```{r sim4p333, message=FALSE }
no_cores <- detectCores()- 1 
cl <- makeCluster(no_cores)
registerDoParallel(cl)

n_sim = 1000
n_trees = 10
MP = matrix(nrow=n_sim,ncol=3)
RP = matrix(nrow=n_sim,ncol=3)
p = proc.time()
ests <- foreach(i = 1:n_sim, .combine=data.frame,.packages='dmea') %dopar% sim_est(n_trees=n_trees,rec_method=3,seed=i,impsam=TRUE)
print(proc.time()-p)

for (i in 1:n_sim){
  RP[i,] = ests[,(2*i-1)]
  MP[i,] = ests[,2*i]
}
stopCluster(cl)
par_est_vis(P=MP,par=1,PR=RP)
par_est_vis(P=MP,par=2,PR=RP)
par_est_vis(P=MP,par=3,PR=RP)

```

```{r sum4p333}
summary(MP)
```

```{r vis333}
par_est_vis(P=MP[MP[,1]<3,],par=1,PR=RP[MP[,1]<3,])
par_est_vis(P=MP[MP[,1]<3,],par=2,PR=RP[MP[,1]<3,])
par_est_vis(P=MP[MP[,1]<3,],par=3,PR=RP[MP[,1]<3,])
```

```{r sum4p0333}
summary(MP[MP[,1]<3,])
```
