---
title: "Computational times"
author: "Jan, 27th"
date: "January 28, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

```{r echo=FALSE, include=FALSE}
library(dmea)
```

## How long it takes to generate a set of trees?

For 10 trees?

```{r}
library(dmea)
set.seed(128)
s = sim_phyl()
#plot(s$newick)
s2 = drop.fossil(s$newick)
s2 = phylo2p(s2)
wt = s2$t
n_trees = 100
pars = c(0.8,0.0175,0.1)
p = proc.time()
S = sim_srt(wt=wt, pars=pars, parallel=F, n_trees=n_trees)
print(proc.time()-p)
```

```{r}
p = proc.time()
pars = subplex(par = pars, fn = llik_st , setoftrees = S)
print(proc.time()-p)
```


For 1000 trees?

```{r}
library(dmea)
set.seed(128)
s = sim_phyl()
#plot(s$newick)
s2 = drop.fossil(s$newick)
s2 = phylo2p(s2)
wt = s2$t
n_trees = 1000
pars = c(0.8,0.0175,0.1)
p = proc.time()
S = sim_srt(wt=wt, pars=pars, parallel=F, n_trees=n_trees)
print(proc.time()-p)
```

```{r}
p = proc.time()
pars = subplex(par = pars, fn = llik_st , setoftrees = S)
print(proc.time()-p)
```


For 1000 parallel?

```{r}
library(dmea)
set.seed(128)
s = sim_phyl()
#plot(s$newick)
s2 = drop.fossil(s$newick)
s2 = phylo2p(s2)
wt = s2$t
n_trees = 1000
pars = c(0.8,0.0175,0.1)
p = proc.time()
S = sim_srt(wt=wt, pars=pars, parallel=T, n_trees=n_trees)
print(proc.time()-p)
```

```{r}
p = proc.time()
pars = subplex(par = pars, fn = llik_st , setoftrees = S)
print(proc.time()-p)
```

For 10000 trees?

```{r}
library(dmea)
set.seed(128)
s = sim_phyl()
#plot(s$newick)
s2 = drop.fossil(s$newick)
s2 = phylo2p(s2)
wt = s2$t
n_trees = 10000
pars = c(0.8,0.0175,0.1)
p = proc.time()
S = sim_srt(wt=wt, pars=pars, parallel=F, n_trees=n_trees)
print(proc.time()-p)
```

```{r}
p = proc.time()
pars = subplex(par = pars, fn = llik_st , setoftrees = S)
print(proc.time()-p)
```


For 10000 parallel?

```{r}
library(dmea)
set.seed(128)
s = sim_phyl()
#plot(s$newick)
s2 = drop.fossil(s$newick)
s2 = phylo2p(s2)
wt = s2$t
n_trees = 10000
pars = c(0.8,0.0175,0.1)
p = proc.time()
S = sim_srt(wt=wt, pars=pars, parallel=T, n_trees=n_trees)
print(proc.time()-p)
```

```{r}
p = proc.time()
pars = subplex(par = pars, fn = llik_st , setoftrees = S)
print(proc.time()-p)
```


**********************

# Computational times of normal simulation functions

```{r}
n_it = 1
a = vector("list", n_it)
# diversity dependence model. parameters are par=c(lambda,mu,K)
time=proc.time()
for (i in 1:(n_it)){
  s = sim_phyl()
  a[[i]] = s$wt
}
t2 = proc.time()-time
paste(t2[3]/60,'min')
```

```{r}
n_it = 10
a = vector("list", n_it)
# diversity dependence model. parameters are par=c(lambda,mu,K)
time=proc.time()
for (i in 1:(n_it)){
  s = sim_phyl()
  a[[i]] = s$wt
}
t2 = proc.time()-time
paste(t2[3]/60,'min')
```

```{r}
n_it = 100
a = vector("list", n_it)
# diversity dependence model. parameters are par=c(lambda,mu,K)
time=proc.time()
for (i in 1:(n_it)){
  s = sim_phyl()
  a[[i]] = s$wt
}
t2 = proc.time()-time
paste(t2[3]/60,'min')
```





